Repository tell-me-team/Back-End, pull requests merged in 2023-08, with the labels that each got.

#12 Feat: [#6] Spring Security 설정 및 OAuth2 인증, 인가 구현
  tellme/build.gradle
  tellme/src/main/java/com/tellme/tellme/TellmeApplication.java
  tellme/src/main/java/com/tellme/tellme/common/config/.gitkeep
  tellme/src/main/java/com/tellme/tellme/common/config/JwtAuthenticationFilter.java
  tellme/src/main/java/com/tellme/tellme/common/config/JwtConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/JwtTokenProvider.java
  tellme/src/main/java/com/tellme/tellme/common/config/RestTemplateConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/SpringSecurityConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/WebConfig.java
  tellme/src/main/java/com/tellme/tellme/common/enums/.gitkeep
  tellme/src/main/java/com/tellme/tellme/common/enums/SocialLoginType.java
  tellme/src/main/java/com/tellme/tellme/common/enums/UserRole.java
  tellme/src/main/java/com/tellme/tellme/common/exception/AuthException.java
  tellme/src/main/java/com/tellme/tellme/domain/BaseEntity.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/KakaoOauth.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/SocialOauth.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/UserDetailsServiceImpl.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthController.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthDto.java
  tellme/src/main/java/com/tellme/tellme/domain/user/application/.gitkeep
  tellme/src/main/java/com/tellme/tellme/domain/user/application/UserService.java
  tellme/src/main/java/com/tellme/tellme/domain/user/entity/User.java
  tellme/src/main/java/com/tellme/tellme/domain/user/persistence/.gitkeep
  tellme/src/main/java/com/tellme/tellme/domain/user/persistence/UserRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserController.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserDto.java
  tellme/src/main/resources/application.yml
Labels: 👨‍💻 Feature, ⚙️ Setting

#17 Feat/#13
  tellme/src/main/java/com/tellme/tellme/common/exception/AuthException.java
  tellme/src/main/java/com/tellme/tellme/common/exception/BaseException.java
  tellme/src/main/java/com/tellme/tellme/common/exception/ErrorStatus.java
  tellme/src/main/java/com/tellme/tellme/common/exception/ExceptionAdvice.java
  tellme/src/main/java/com/tellme/tellme/common/exception/SurveyException.java
  tellme/src/main/java/com/tellme/tellme/common/exception/UserException.java
  tellme/src/main/java/com/tellme/tellme/common/response/BaseExceptionResponse.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthController.java
  tellme/src/main/java/com/tellme/tellme/domain/user/application/UserService.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserDto.java
Labels: 👨‍💻 Feature

#19 Feat/#16
  tellme/src/main/java/com/tellme/tellme/common/config/JwtConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/SpringSecurityConfig.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/entity/SurveyShortUrl.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserControllerV1.java
  tellme/src/main/java/com/tellme/tellme/healcheck/HealthcheckController.java
Labels: 🕷 Bug, 👨‍💻 Feature

#21 Feat:[#14] 인증 필터 예외처리 구현
  tellme/src/main/java/com/tellme/tellme/common/auth/CustomAccessDeniedHandler.java
  tellme/src/main/java/com/tellme/tellme/common/auth/CustomAuthenticationEntryPoint.java
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtAuthenticationFilter.java
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtConfig.java
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtTokenProvider.java
  tellme/src/main/java/com/tellme/tellme/common/auth/SpringSecurityConfig.java
  tellme/src/main/java/com/tellme/tellme/common/exception/ErrorStatus.java
  tellme/src/main/java/com/tellme/tellme/common/exception/ExceptionAdvice.java
  tellme/src/main/java/com/tellme/tellme/common/response/BaseExceptionResponse.java
  tellme/src/main/java/com/tellme/tellme/common/response/BaseResponse.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/user/application/UserService.java
  tellme/src/main/resources/application.yml
Labels: 👨‍💻 Feature

#29 CORS 및 필터 예외처리 에러 수정
  .github/workflows/eb-cd.yml
  README.md
  tellme/.gitignore
  tellme/Dockerfile
  tellme/build.gradle
  tellme/docker-compose.yml
  tellme/src/main/java/com/tellme/tellme/common/auth/CustomAuthenticationEntryPoint.java
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtAuthenticationFilter.java
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtTokenProvider.java
  tellme/src/main/java/com/tellme/tellme/common/auth/SpringSecurityConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/WebConfig.java
  tellme/src/main/java/com/tellme/tellme/common/enums/UserRole.java
  tellme/src/main/java/com/tellme/tellme/common/exception/ExceptionAdvice.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/UserDetailsServiceImpl.java
  tellme/src/main/java/com/tellme/tellme/domain/user/entity/User.java
  tellme/src/main/java/com/tellme/tellme/domain/user/persistence/UserRepository.java
  tellme/src/main/resources/application.yml
Labels: 🕷 Bug

#31 Feat/#26
  tellme/src/main/java/com/tellme/tellme/common/exception/ErrorStatus.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
Labels: 👨‍💻 Feature

#33 Feat/#32 login response picture data 추가
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthDto.java
Labels: 👨‍💻 Feature

#35 Bug:[#34] CI/CD 설정 수정
  .github/workflows/deploy.yml
  tellme/build.gradle
  tellme/src/main/java/com/tellme/tellme/TellmeApplication.java
  tellme/src/main/resources/application.yml
  tellme/src/main/resources/env.properties
Labels: 🕷 Bug, 📃 Document

#37 Feat/#7
  tellme/src/main/java/com/tellme/tellme/common/exception/ErrorStatus.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/entity/SurveyAnswer.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/entity/SurveyCompletion.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/entity/SurveyResult.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/QuestionRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/SurveyCompletionRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1.java
Labels: 👨‍💻 Feature

#36 feat : url 디코드 api user nickname 추가
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
Labels: 👨‍💻 Feature

#38 bug [#7] : 설문 답변 readonly 설정되어있던 부분 수정
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
Labels: 🕷 Bug

#48 Bug/#47 기존 cors 설정 삭제 및 spring security cors 설정 추가
  tellme/src/main/java/com/tellme/tellme/common/auth/CorsConfig.java
  tellme/src/main/java/com/tellme/tellme/common/auth/SpringSecurityConfig.java
  tellme/src/main/java/com/tellme/tellme/common/config/WebConfig.java
Labels: 🕷 Bug

#50 Fix/survey
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/SurveyCompletionRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
Labels: 🕷 Bug

#53 Docs:[#52] swaager 설정 변경(header 및 description 추가)
  tellme/src/main/java/com/tellme/tellme/common/config/SwaggerConfig.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserControllerV1.java
  tellme/src/main/java/com/tellme/tellme/healcheck/HealthcheckController.java
Labels: 📃 Document

#54 Bug/#49
  tellme/src/main/java/com/tellme/tellme/common/config/SwaggerConfig.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/entity/SurveyAnswer.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserControllerV1.java
  tellme/src/main/java/com/tellme/tellme/healcheck/HealthcheckController.java
Labels: 🕷 Bug

#55 Bug:[#49] user info response에 수행한 내 설문 데이터 추가
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/SurveyCompletionRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/user/application/UserService.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserDto.java
Labels: 🕷 Bug

#58 Test/#56
  tellme/build.gradle
  tellme/src/main/java/com/tellme/tellme/common/auth/JwtTokenProvider.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/application/OAuthService.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/auth/presentation/AuthDto.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/application/SurveyService.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/SurveyCompletionRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/persistence/SurveyShortUrlRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/SurveyDto.java
  tellme/src/main/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1.java
  tellme/src/main/java/com/tellme/tellme/domain/user/application/UserService.java
  tellme/src/main/java/com/tellme/tellme/domain/user/entity/User.java
  tellme/src/main/java/com/tellme/tellme/domain/user/persistence/UserRepository.java
  tellme/src/main/java/com/tellme/tellme/domain/user/presentation/UserControllerV1.java
  tellme/src/main/resources/application.yml
  tellme/src/test/java/com/tellme/tellme/TellmeApplicationTests.java
  tellme/src/test/java/com/tellme/tellme/domain/auth/application/OAuthServiceTest.java
  tellme/src/test/java/com/tellme/tellme/domain/auth/presentation/AuthControllerV1Test.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/application/SurveyServiceTest.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/persistence/QuestionRepositoryTest.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/persistence/SurveyCompletionRepositoryTest.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/persistence/SurveyQuestionQueryRepositoryTest.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/persistence/SurveyShortUrlRepositoryTest.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/persistence/TestQueryConfig.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/presentation/SurveyControllerV1Test.java
  tellme/src/test/java/com/tellme/tellme/domain/survey/presentation/UserSurveyControllerV1Test.java
  tellme/src/test/java/com/tellme/tellme/domain/user/application/UserServiceTest.java
  tellme/src/test/java/com/tellme/tellme/domain/user/persistence/UserRepositoryTest.java
  tellme/src/test/java/com/tellme/tellme/domain/user/presentation/UserControllerV1Test.java
  tellme/src/test/resources/application.yml
  tellme/src/test/resources/sql/auth-controller-test-data.sql
  tellme/src/test/resources/sql/auth-service-test-data.sql
  tellme/src/test/resources/sql/delete-all-data.sql
  tellme/src/test/resources/sql/survey-controller-test-data.sql
  tellme/src/test/resources/sql/survey-repository-test.sql
  tellme/src/test/resources/sql/survey-service-test-data.sql
  tellme/src/test/resources/sql/user-controller-test-data.sql
  tellme/src/test/resources/sql/user-repository-test-data.sql
  tellme/src/test/resources/sql/user-service-test-data.sql
Labels: 🛠 Refactoring, ✅ Test
